language: csharp
mono: none
jobs:
  include:
    # Linux: tests, releases, coverage
    - os: linux
      env: TEST_ARGS="-p:CollectCoverage=true -p:CoverletOutputFormat=opencover"
      dotnet: 3.1.3
      before_script:
        - ./setup stable
        - ./scripts/solution
      script:
        - dotnet test build $TEST_ARGS
        - sudo ./scripts/dev-workflow-test
      after_script:
        - sed -i 's/.cs/.howl/g' build/test/coverage.opencover.xml
        - bash <(curl -s https://codecov.io/bash)
      before_deploy: ./scripts/archive
      deploy:
        provider: releases
        api_key: $github_token
        file: "howl.tgz"
        skip_cleanup: true
        on:
          tags: true
      after_deploy:
        script: ./setup
    # Windows: tests only
    - os: windows
      env: TEST_ARGS="-l console;verbosity=normal"
      before_script:
        - powershell Set-ExecutionPolicy Unrestricted
        - choco install dotnetcore-sdk
        - powershell "./setup.ps1 stable"
        - powershell howl build .
      script: dotnet test build $TEST_ARGS
