language: csharp
dotnet: 3.1.3
mono: none
before_script:
    - ./setup
    - ./scripts/solution
script:
    - sudo dotnet test build -c Release -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
after_script:
    - bash <(curl -s https://codecov.io/bash)
