language: csharp
dotnet: 2.2.401
mono: none
before_script:
    - ./setup
    - ./scripts/solution
script:
    - dotnet test build -c Release -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
after_script:
    - bash <(curl -s https://codecov.io/bash)
