language: csharp
dotnet: 3.1.3
mono: none
before_script:
    - ./setup
    - ./scripts/solution
script:
    - dotnet test build -c Release -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
after_script:
    - sed -i 's/.cs/.howl/g' build/test/coverage.opencover.xml
    - bash <(curl -s https://codecov.io/bash)
