language: csharp
mono: none
script: dotnet test build $TEST_ARGS
jobs:
    include:
      - os: windows
        env: TEST_ARGS="-l console;verbosity=detailed"
        before_script:
            - powershell Set-ExecutionPolicy Unrestricted
            - choco install dotnetcore-sdk
            - powershell "./setup.ps1"
            - powershell howl build .
      - os: linux
        env: TEST_ARGS="-p:CollectCoverage=true -p:CoverletOutputFormat=opencover"
        dotnet: 3.1.3
        before_script:
            - ./setup
            - ./scripts/solution
        after_script:
            - sed -i 's/.cs/.howl/g' build/test/coverage.opencover.xml
            - bash <(curl -s https://codecov.io/bash)
