#!/bin/bash
set -euo pipefail
apt-get update -qq
apt-get install -qq wget &> /dev/null
wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
dpkg -i packages-microsoft-prod.deb &> /dev/null
apt-get update -qq
apt-get install -qq apt-transport-https
DEBIAN_FRONTEND=noninteractive apt-get install -qq dotnet-sdk-3.1
