#!/bin/bash
# -------------------------------------------------------------------
version=0.1.1
repo=https://github.com/active-logic/howl
url=$repo/releases/download/$version/howl.tgz
# -------------------------------------------------------------------
echo -e "GET http://google.com HTTP/1.0\n\n" \
                                  | nc google.com 80 > /dev/null 2>&1
if [ $? -eq 1 ]; then
    echo "Cannot run setup while offline" && exit $?
fi
# -------------------------------------------------------------------
set -euo pipefail
mkdir -p /usr/local/bin             # Catalina: ensure /usr/local/bin
if command -v apt-get &> /dev/null
then                                # Linux: get sudo and dotnet sdk
    flags=""
    apt-get update -qq && apt-get install -qq sudo
    if ! command -v dotnet &> /dev/null
    then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/active-logic/howl/master/install_dotnet)"
    fi
else flags="-r osx-x64"             # macOS: set publish RID
fi
# -------------------------------------------------------------------
mkdir howl
curl  -Ls $url | tar xz --strip 1 -C howl
pushd howl/src > /dev/null
sudo  rm -rf /usr/local/Howl
sudo  dotnet publish --nologo -v quiet $flags -o /usr/local/Howl
sudo  ln -sf /usr/local/Howl/src /usr/local/bin/howl
popd  > /dev/null
sudo  rm -rf howl
howl
