#!/bin/bash
version=0.1.0
repo=https://github.com/active-logic/howl
url=$repo/releases/download/$version/howl.tgz
mkdir /usr/local/bin  # for Catalina (test)
set -euxo pipefail
if command -v apt-get &> /dev/null
then
    flags=""
    apt-get update -qq
    apt-get install -qq sudo
    if ! command -v dotnet &> /dev/null
    then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/active-logic/howl/master/install_dotnet)"
    fi
else flags="-r osx-x64"
fi
mkdir howl
curl  -Ls $url | tar xz --strip 1 -C howl
pushd howl/src > /dev/null
sudo  rm -rf /usr/local/Howl
sudo  dotnet publish --nologo -v quiet $flags -o /usr/local/Howl
sudo  ln -sf /usr/local/Howl/src /usr/local/bin/howl
popd  > /dev/null
sudo  rm -rf howl
howl
