#!/bin/bash
set  -euo pipefail
cd   "$(git rev-parse --show-toplevel)"
echo "Installing local version"
howl install . > /dev/null
echo "Running tests"
echo "- export..."  && howl export src tmp > /dev/null && rm -rf tmp
echo "- build...."  && howl build   .  > /dev/null
echo "- run......"  && howl run     .  > /dev/null
echo "- test....."  && howl test    .  > /dev/null
# Disable for now as this may cause a segfault (intermittent)
# echo "- install.."  && howl install .  > /dev/null
# All done
echo "OK"
