#!/bin/bash
# Usage: cd Howl && ./scripts/gup [major/minor/patch]
# Requires ../Tree-Sitter and Atom with language-howl
if [ $# -eq 0 ]
  then
    echo "Missing argument: gup (major | minor | patch)" && exit 1
fi
case $1 in
  "major") ;; "minor") ;; "patch") ;;
   *) echo "Invalid argument: $1" && exit 1 ;;
esac
set         -euo pipefail
howl        install .
howl        shorthands docs/snippets.md
pushd       ../Tree-Sitter
howl        inject grammar.template.js grammar.js
tree-sitter generate
tree-sitter parse example.howl
tree-sitter parse sample.howl
tree-sitter parse braces.howl
git         add --all
git         commit -m "Update grammar"
git         push
npm         version $1
npm         publish
popd
# Copy engine files to Uta
./scripts/patch-uta
# Info for manual steps
echo "Next, cd to ~/.atom/packages/language-howl/, "
echo "bump tree-sitter-howl version in package.json and"
echo "run 'apm install --verbose' to ensure language-howl"
echo "is using the latest grammar."
