#!/bin/bash
set  -euo pipefail
cd   "$(git rev-parse --show-toplevel)"
echo "Copy sources to Uta"
pushd ../Uta/Assets/Howl
rm -rf Editor/Ng ~build/Howl/Editor/Ng
popd
pushd ..
cp -r Howl/src       Uta/Assets/Howl/Editor/Ng
cp -r Howl/build/src Uta/Assets/Howl/~build/Howl/Editor/Ng
popd
# Delete both derived products and cli/versioning related
pushd ../Uta/Assets/Howl/~build/Howl/Editor/Ng
rm -rf bin obj cli versioning src.csproj
popd
pushd ../Uta/Assets/Howl/Editor/Ng
rm -rf cli versioning src.csproj
popd
